
  CREATE TABLE "SYSTEM"."BOOK" 
   (	"BID" VARCHAR2(20 BYTE), 
	"BNAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"PRICE" NUMBER DEFAULT NULL, 
	"AUTHOR" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"IMAGE" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"CID" NUMBER(*,0) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
