
  CREATE TABLE "SYSTEM"."ORDERS" 
   (	"OID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ORDERTIME" TIMESTAMP (6) DEFAULT NULL, 
	"TOTAL" NUMBER(10,2) DEFAULT NULL, 
	"STATE" NUMBER(*,0) DEFAULT NULL, 
	"USERID" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"ADDRESS" VARCHAR2(200 BYTE) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
