
  CREATE TABLE "SYSTEM"."ORDERITEM" 
   (	"IID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"COUNT" NUMBER(*,0) DEFAULT NULL, 
	"SUBTOTAL" NUMBER(10,2) DEFAULT NULL, 
	"OID" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"BID" VARCHAR2(50 BYTE) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
